### PR TITLE
Fixes minor typo in `tutorials/colab/DeepHyper_101.ipynb`

### PR DESCRIPTION
**Pull request by saforem2**
`dictionnary -> dictionary`

### CODE REVIEW

**Comment by Deathn0t** [comment]
Hello @saforem2 , thank you for submitting this PR. It looks like the diff is much larger than the typo announced in the description. Could you summarise what/why some things have been changed (first import/install cell, final plot, %time statement)?

**Comment by saforem2** [comment]
Shoot sorry, I meant to elaborate in the body but changes include:

1. Wrap `!pip install deephyper` in a `try/except` block that first attempts to `import deephyper` and only installs if not found
2. Minor changes to plot style (grey lines / text for visibility in light / dark mode)

**Comment by Deathn0t** [comment]
Light/dark mode is a good idea. maybe we should provide some style guidelines to remember about doing this everywhere (do not need to be complex). On [this page](https://deephyper.readthedocs.io/en/latest/developer_guides/doc.html) for example.

**Comment by Deathn0t** [comment]
I added a small comment about something I just noticed... If you could edit this it would be great and then I merge. Thank you.

**Comment by saforem2** [comment]
> I added a small comment about something I just noticed... If you could edit this it would be great and then I merge. Thank you.

Sorry, where did you add a comment?

**Comment by saforem2** [comment]
fwiw, I made a [gist](https://gist.github.com/saforem2/62d777eb022fe228921345c7eb5859ac) with the `.mplstyle` file I used if you're interested

**Comment by Deathn0t** [comment]
here it is @saforem2 I forgot to validate the review...

**Pull request merged**
